import type { Metadata } from "next"
import { Marcellus, Nunito_Sans } from "next/font/google"
import "./globals.css"

const marcellus = Marcellus({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-marcellus",
	weight: ["400"],
})

const nunito = Nunito_Sans({
	subsets: ["latin"],
	variable: "--font-nunito",
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="es" className={`${marcellus.variable} ${nunito.variable}`}>
			<body className="bg-bg-site text-main font-sans antialiased">
				{children}
			</body>
		</html>
	)
}
